### ISSUE TITLE
data2bids does not work.

### ISSUE THREAD

**Issue by schoffelen** [Donders-Institute/staff-scientists#1]
**Describe the issue**
A clear and concise description of the issue.

**Describe yourself**
1. Name
2. Function
3. PI group

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment and versions (please complete the following information):**
 - Operating System: [e.g. Linux, Windows 10]
 - Analysis software: [e.g. MATLAB, FSL, R]
 - Software version.

**Additional context**

**Comment by schoffelen** [comment]
this is a phony bug, to check whether notifications etc. work.

**Comment by marcelzwiers** [comment]
Well, depends who you ask

**Comment by schoffelen** [comment]
I got the e-mail at least :) So that works!
