### ISSUE TITLE
Defacing Multi-echo gradient datasets

### ISSUE THREAD

**Issue by JosePMarques** [Donders-Institute/staff-scientists#2]
**Describe the issue**
The multiple images of multi-echo gradient echo sequences are currently defaced independently using BIDSCOIN. That results in some inconsistent masking that affects derived metrics such as R2* and QSM

**Describe yourself**
1. Jose Marques and Jitse Amelink
2. aPI and RA
3. David Norris & Christian Beckmann

**To Reproduce**
To see the effect on resulting maps go to 
/project/3022026.02/POM/bids/derivatives/R2QSM_Analysis/slicesdir_r2star/index.html
/project/3022026.02/POM/bids/derivatives/R2QSM_Analysis/slicesdir_ndi/index.html
you can see artifacts on, for example:
'sub-POMU20556DDE047C589F';
'sub-POMUAE1E4F5C75D1523C';
'sub-POMUEED344D99F59534D';
'sub-POMU184AA121F3E8D5E5'
'sub-POMU1CA754739B57B126'
'sub-POMU20075E6786088974'
I expect this to also be a problem on the ABRIM and Healthy brain projects

**Expected behavior**
Ideally the defacing of one protocol should be consistent for all images of that protocol;

**Screenshots**
this is an example of a poorly defaced image (echo time number 7)
![image](https://user-images.githubusercontent.com/19411903/122187005-ea820700-ce8e-11eb-9efe-eeb56a042643.png)
this is on the same subject the correctly defaced mask for the first 6 echo times: 
![image](https://user-images.githubusercontent.com/19411903/122187168-143b2e00-ce8f-11eb-90d6-3ab2329a45f9.png)

**Environment and versions (please complete the following information):**
 - Operating System: linux
 - Analysis software: bidscoin
 - Software version; 3.5 and 3.6

**Additional context**

**Comment by marcelzwiers** [comment]
I [finished](https://github.com/Donders-Institute/bidscoin/commit/7a4218552e15eeb75d603281877ea3a8faa73de1) implementing the multi-echo `medeface` tool and it worked as expected. It will be in the new bidscoun release but till then you can find and test it using `module add bidscoin/dev`.
