### ISSUE TITLE
Running fmriprep: freesurfer crash autorecon1

### ISSUE THREAD

**Issue by Ldenooij** [Donders-Institute/staff-scientists#21]
**Describe the issue**
When I run fmriprep, the pipeline crashes when preprocessing the anatomical (T1 weighted scan) at the autorecon1 node.

The terminal says:
```
230110-10:05:47,972 nipype.workflow INFO:
     [Node] Setting-up "fmriprep_wf.single_subject_001_wf.anat_preproc_wf.brain_extraction_wf.atropos_wf.apply_mask" in "/project/3013091.01/fmriprep_work/sub-001/fmriprep_wf/single_subject_001_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/apply_mask".
230110-10:05:48,5 nipype.workflow INFO:
     [Node] Setting-up "_apply_mask0" in "/project/3013091.01/fmriprep_work/sub-001/fmriprep_wf/single_subject_001_wf/anat_preproc_wf/brain_extraction_wf/atropos_wf/apply_mask/mapflow/_apply_mask0".
230110-10:05:48,51 nipype.workflow INFO:
     [Node] Running "_apply_mask0" ("niworkflows.interfaces.nibabel.ApplyMask")
230110-10:05:48,686 nipype.workflow INFO:
     [Node] Finished "_apply_mask0".
230110-10:05:48,699 nipype.workflow INFO:
     [Node] Finished "fmriprep_wf.single_subject_001_wf.anat_preproc_wf.brain_extraction_wf.atropos_wf.apply_mask".
230110-10:05:51,899 nipype.workflow ERROR:
     could not run node: fmriprep_wf.single_subject_001_wf.anat_preproc_wf.surface_recon_wf.autorecon1
230110-10:05:51,919 nipype.workflow CRITICAL:
     fMRIPrep failed: Workflow did not execute cleanly. Check log for details
230110-10:05:52,604 cli ERROR:
     Preprocessing did not finish successfully. Errors occurred while processing data from participants: 001 (1). Check the HTML reports for details.
```
The subject report says:
ERROR
Node Name: fmriprep_wf.single_subject_001_wf.anat_preproc_wf.surface_recon_wf.autorecon1

**Describe yourself**
1. Laura de Nooij
2. PhD candidate
3. Erno Hermans

**Audience**
Everyone or some people using fmriprep and/or freesurfer?

**Test data**
You can find a test dataset that illustrates the issue here: '..'

**To Reproduce**
1. Go to HPC cluster
2. Submit job (see code below)
3. Wait ~1.5 hours until it crashes
4. See error in terminal, html file and search for working directory file (autorecon1)

**Expected behavior**
Run and finish preprocessing without crashing

**Screenshots**
Not applicable

**Environment and versions (please complete the following information):**
 - Operating System: Linux / HPC cluster
 - Analysis software: fmriprep & freesurfer
 - fmriprep v20.3.2, calls freesurfer default

**Additional context**
I have tried both submitting a job via the wrapper function, or analysing directly in an interactive node. 
It also does not matter whether I specify a working directory or not.

code (using wrapper function)
fmriprep_sub.py /project/3013091.01/bids -o /project/3013091.01/fmriprep -w /project/3013091.01/fmriprep_work -p 001 -m 64000 -n 3 -a " --skip-bids-validation --fs-license-file /opt_host/fmriprep/license.txt --mem_mb 64000 --use-aroma --ignore slicetiming --output-spaces MNI152NLin6Asym T1w"

 I will continue by verifying the following steps:
- Does it matter whether I use another version of fmriprep?
- Does it matter which output spaces I specify?
- Does it run if I don't specify freesurfer?

**Comment by schoffelen** [comment]
Hoi Laura, perhaps it's best to drop by at our office at some point. We need to inspect the logs in a bit more detail than the details that are provided by fmriprep. That's not your fault, but results from fmriprep not being sufficiently informative. We are in office 01.158...

**Comment by schoffelen** [comment]
there's no trace of how it was solved, but it has been solved
