### ISSUE TITLE
bids_T1B1.m to correct mp2rage image does not run.

### ISSUE THREAD

**Issue by atstak** [Donders-Institute/staff-scientists#4]
**Describe the issue**
While trying to run bids_T1B1.m on matlab, the script gives me an error message at line 191. Error message: Interpolation requires at least two sample points for each grid dimension. If numbers 

**Describe yourself**
1. Atsuko Takashima
2. Postdoc
3.  Neurobiology of Language

**To Reproduce**
1. Run bids_T1B1.m with the inputs as explained in the help
2. Error using matlab.internal.math.interp1
Interpolation requires at least two sample points for each grid dimension.
 
Error in interp1 (line 188)
        VqLite = matlab.internal.math.interp1(X,V,method,method,Xqcol);
 
Error in T1B1correctpackageTFL (line 128)
    MP2RAGEmatrix(k,:)    = interp1(T1vector, Intensity, T1_vector);
 
Error in bids_T1B1correct (line 191)
    [T1map, MP2RAGECorr] = T1B1correctpackageTFL(B1img, MP2RAGEimg, [], MP2RAGE{n}, [], InvEff);

**Expected behavior**
When given numbers recommended by José, after this line, the script runs smoothly.
MP2RAGE.nZslices = [86 114]
MP2RAGE.TRFLASH = 0.0074;

It seems with the current script, it uses MP2RAGE_lookuptable.m and gets the numbers 
MP2RAGE{1,1}.TRFLASH  = 0.0066
MP2RAGE{1,1}.NZslices = 288

**Screenshots**
![image](https://user-images.githubusercontent.com/52576461/125458952-fdca35bd-e6b8-453c-8283-7ab774d3643b.png)

**Environment and versions (please complete the following information):**
 - Operating System: mentat cluster
 - Analysis software: MATLAB 
 - Software version: R2021a

**Additional context**
This has been discussed between Marcel, José and me in the emails between 5th to 19th May 2021

**Comment by schoffelen** [comment]
Hi Atsuko,

I suggest to also provide (a summary of) the e-mail exchange here for documentation.
Also, I guess your issue is the consequence of an interaction between code, and data. What's the data that causes you problems?

**Comment by schoffelen** [comment]
Also - for reference - the code that gives you troubles is stuff that has to do with the following repo: https://github.com/JosePMarques/MP2RAGE-related-scripts

**Comment by atstak** [comment]
Hi Jan-Mathijs,

I just had a quick chat with Marcel by the canteen, and he suggested me to put this up by creating an issue so that he can work on it after he is back from the vacation.
It is indeed the mp2rage related scripts, and it seems that Marcel’s wrapper does not assign correct numbers to be read out from the data header to be used in the script.
The email correspondence is already summarized in the Expected behavior part.
Let me know what further needs to be done (as I am not quite acquainted with this system…)

Atsuko

**Comment by marcelzwiers** [comment]
Let me make sure if I understand this correctly, you edited the code and inserted those numbers? Did you also try to pass the value to the `NrShots` input argument of bids_T1B1correct()? Because that's what you should do if leaving it empty gives a wrong estimate...

**Comment by marcelzwiers** [comment]
The same holds for the TRFLASH, you can use the `EchoSpacing` input argument there...

**Comment by atstak** [comment]
Dear Marcel,

So I should enter the values for MP2RAGE.NZslices (in my case [86 114]) in the second argument of the input (NrShots), and MP2RAGE.TRFLASH (in my case 0.0074) as the third argument of the input (EchoSpacing)?
I did this, and this time the script ran.

My excuses that I did not know that NrShots meant the values for NZslices and EchoSpacing was about TRFLASH values.

Atsuko

**Comment by marcelzwiers** [comment]
> Dear Marcel, So I should enter the values for MP2RAGE.NZslices (in my case [86 114]) in the second argument of the input (NrShots), and MP2RAGE.TRFLASH (in my case 0.0074) as the third argument of the input (EchoSpacing)? I did this, and this time the script ran. My excuses that I did not know that NrShots meant the values for NZslices and EchoSpacing was about TRFLASH values.
Well, that's probably because Jose uses both terms through one another and he gave you the other one? In the help I use one term only... @JosePMarques what is the best here, do I need to update the help?

**Comment by JosePMarques** [comment]
Basically my code is pre-BIDS (and is associated with the nomenclature used in my manuscript) and the BIDS wrappers are post BIDS… not sure what the best solution is.
Maybe extending the help with some more examples on how the NrShots can be retrieved and mentioning that echo spacing is in this sequence equivalent to the TR of the FLASH readout would be the simplest solution.

**Comment by marcelzwiers** [comment]
I changed the default for NrShots to: nr of z-slices and updated the help-text to avoid the confusion. See aa924a0537eb7f48fb7e70d08e1d7b6bc7b42a84
