### ISSUE TITLE
figure exportation to pdf does not work with qsubfeval

### ISSUE THREAD

**Issue by schoffelen** [Donders-Institute/staff-scientists#6]
**Describe the issue**
Figure export to pdf in matlab does not work well when using qsubcellfun/qsubfeval, in an interactive matlab session all is fine.

**Describe yourself**
1. Britta Westner
2. postdoc
3. PI: Floris de Lange

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment and versions (please complete the following information):**
 - Operating System: [e.g. Linux, Windows 10]
 - Analysis software: [e.g. MATLAB, FSL, R]
 - Software version.

**Additional context**
This has been already discussed through Mattermost with JM, a solution has been found, and will be documented

**Comment by schoffelen** [comment]
pinging @britta-wstnr, no action needed

**Comment by schoffelen** [comment]
Minimum working example:

%%%%%%%%%%%%%%%%%%%%%%%%%%%
function run_sourceplot(savename)

name = dccnpath('/home/common/matlab/fieldtrip/data/Subject01.mri');
mri = ft_read_mri(fname);

krn = strel('sphere',5);
krn = double(krn.Neighborhood);
mri.pow = convn(randn(mri.dim), krn, 'same');

cfg = [];
cfg.funparameter = 'pow';
ft_sourceplot(cfg,mri);
print(gcf,'-dpdf',savename);
close all
%%%%%%%%%%%%%%%%%%%%%%%%%

- running the above in an interactive matlab session creates a pdf-file that renders well
- running qsubfeval('run_sourceplot','test.pdf','memreq',4 * 1024^3,'timreq',10*60); creates a pdf-file that does not render well

**Comment by marcelzwiers** [comment]
>> addpath('/home/common/matlab/fieldtrip')
>> run_sourceplot('test')
Unrecognized function or variable 'dccnpath'.

Error in run_sourceplot (line 3)
name = dccnpath('/home/common/matlab/fieldtrip/data/Subject01.mri');

**Comment by schoffelen** [comment]
No worries Marcel, this requires the user to have fieldtrip on the matlab path, and initialized:

addpath /home/common/matlab/fieldtrip;
ft_defaults;

By the way, the solution is:

qsubfeval('run_sourceplot', 'test', <resources>, 'display', 'yes');

That is, only of the interactive matlab is started typing  matlab<version>, rather than matlab in the shell. This latter thing needs to be confirmed btw.

**Comment by marcelzwiers** [comment]
`<resources>`?

**Comment by schoffelen** [comment]
```matlab
qsubfeval('run_sourceplot', 'test','memreq',4*1024^3,'timreq',10*60, 'display', 'yes');
```

**Comment by schoffelen** [comment]
if you want to reproduce, omit the the 'display', 'yes' key-value pair

**Comment by marcelzwiers** [comment]
It renders fine but the orientation is wrong?
![image](https://user-images.githubusercontent.com/15156015/127983906-45e4d8e3-6dba-4e1a-a299-fbd3067917b7.png)

**Comment by schoffelen** [comment]
The orientation is not really wrong, which is explained here: https://www.fieldtriptoolbox.org/faq/my_mri_is_upside_down_is_this_a_problem/
self-advertisement, one of my better pieces of documentation, if I may say so (particularly with the accompanying figures).
No, the issue is that the expected rendering should have a color-coded overlay, with opacity masking. The software opengl seems to screw up here. In the past I encountered a similar problem (with the human connectome project), and back then we needed to use virtual frame buffers to get the stuff fixed (that was running on an architecture that ran a compiled version of matlab + fieldtrip). Here, it seems sufficient for now, to add the 'display', 'yes' key-value pair.

But, I suggest to not spend too much time on it, since the issue was intended as a placeholder for documenting the solution (which Britta and I found already), and to confirm (and look into) the observation that the solution does not work if interactive matlab is started as 'matlab', rather than 'matlab2020b' or so.

**Comment by marcelzwiers** [comment]
Well, I was curious :-). And the feval display option doesn't add an overlay for me

**Comment by schoffelen** [comment]
bummer!

**Comment by marcelzwiers** [comment]
The reason for my curiosity are my historical attempts to have a virtual frame buffer (vfb) running to get better scaling / default screen resolution. But perhaps this is something else

**Comment by schoffelen** [comment]
well, at least the current solution doesn't seem work robustly as of yet, so to be continued

**Comment by marcelzwiers** [comment]
Perhaps it's the old OS / driver and it will go away once the TG upgrades to RHEL?

**Comment by schoffelen** [comment]
for the record: for me running qsubfeval works with 'display','yes' (the job ended up on dccn-c036.dccn.nl), without specifying 'display','yes' it didn't work (also on dccn-c036.dccn.nl).

**Comment by schoffelen** [comment]
I have updated (currently in the FT master branch, once the tests have passed also in the release branch) the functionality of ft_sourceplot, so that with cfg.maskstyle = 'colormix', and cfg.method = 'ortho', the functional color-coded values render nicely in the exported pdf. See: https://github.com/fieldtrip/fieldtrip/pull/1845

What is yet still unresolved, is why the other 'fix' does not work for @marcelzwiers , and also why the other fix does not work if the interactive matlab session is started as matlab, rather than matlab2020b or so.

For now, I don't think that it deserves extra time spent on this, so I suggest to close the issue. Feel free to reopen if you disagree.
